In [30]:
from keras.datasets import mnist
import numpy as np
import matplotlib.pyplot as plt

In [31]:
from keras.utils import to_categorical

In [32]:
from keras.layers import Conv2D,MaxPooling2D,Flatten

In [33]:
(xtrain,ytrain),(xtest,ytest)=mnist.load_data()

In [34]:
xtrain.shape

(60000, 28, 28)

In [35]:
from keras.models import Sequential
from keras.layers import Dense,Activation,Dropout

In [36]:
g=len(np.unique(ytrain))
g

10

In [37]:
np.unique(ytrain)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [38]:
print(ytrain)

[5 0 4 ... 5 6 8]


In [39]:
ytrain=to_categorical(ytrain)
ytest=to_categorical(ytest)
ytrain

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [40]:
z=xtrain.shape[1]
z

28

In [41]:
xtrain=np.reshape(xtrain,[-1,z,z,1])
xtest=np.reshape(xtest,[-1,z,z,1])
xtrain.shape

(60000, 28, 28, 1)

In [42]:
xtest.shape

(10000, 28, 28, 1)

In [43]:
xtrain=xtrain.astype("float32")/255
xtest=xtest.astype("float32")/255

In [44]:
d=(z,z,1)
batchsize=128
kernalsize=3
poolsize=2
filters=64
dropout=0.2


In [45]:
model=Sequential()
model.add(Conv2D(filters=filters,kernel_size=kernalsize,activation="relu",input_shape=d))
model.add(MaxPooling2D(poolsize))
model.add(Conv2D(filters=filters,kernel_size=kernalsize,activation="relu"))
model.add(MaxPooling2D(poolsize))
model.add(Conv2D(filters=filters,kernel_size=kernalsize,activation="relu"))
model.add(Flatten())
model.add(Dropout(dropout))
model.add(Dense(g))
model.add(Activation("softmax"))
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_3 (Conv2D)           (None, 26, 26, 64)        640       
                                                                 
 max_pooling2d_2 (MaxPoolin  (None, 13, 13, 64)        0         
 g2D)                                                            
                                                                 
 conv2d_4 (Conv2D)           (None, 11, 11, 64)        36928     
                                                                 
 max_pooling2d_3 (MaxPoolin  (None, 5, 5, 64)          0         
 g2D)                                                            
                                                                 
 conv2d_5 (Conv2D)           (None, 3, 3, 64)          36928     
                                                                 
 flatten_1 (Flatten)         (None, 576)              

In [46]:
model.compile(loss="categorical_crossentropy",optimizer="sgd",metrics=["accuracy"])
model.fit(xtrain,ytrain,epochs=10,batch_size=batchsize)

Epoch 1/10


469/469 [==============================] - 25s 51ms/step - loss: 1.6432 - accuracy: 0.5161
Epoch 2/10
469/469 [==============================] - 24s 52ms/step - loss: 0.4205 - accuracy: 0.8726
Epoch 3/10
469/469 [==============================] - 24s 52ms/step - loss: 0.2795 - accuracy: 0.9167
Epoch 4/10
469/469 [==============================] - 25s 53ms/step - loss: 0.2137 - accuracy: 0.9358
Epoch 5/10
469/469 [==============================] - 25s 53ms/step - loss: 0.1787 - accuracy: 0.9462
Epoch 6/10
469/469 [==============================] - 24s 51ms/step - loss: 0.1558 - accuracy: 0.9532
Epoch 7/10
469/469 [==============================] - 24s 52ms/step - loss: 0.1401 - accuracy: 0.9574
Epoch 8/10
469/469 [==============================] - 25s 52ms/step - loss: 0.1264 - accuracy: 0.9619
Epoch 9/10
469/469 [==============================] - 24s 52ms/step - loss: 0.1176 - accuracy: 0.9638
Epoch 10/10
469/469 [==============================] - 24s 52ms/step - loss: 0.1

In [47]:
loss,accuracy=model.evaluate(xtest,ytest,batch_size=batchsize)

79/79 [==============================] - 2s 17ms/step - loss: 0.0738 - accuracy: 0.9776


In [48]:
print("\n test accuracy : %.1f%%" %(100.0*accuracy))


 test accuracy : 97.8%
